### PR TITLE
Implement Spiral2D

### PR DESCRIPTION
**Pull request by gmlewis**

### CODE REVIEW

**Comment by deadsy** [comment]
Should the spiral specification be more general? ie - you have r= theta, but in general you have r = m * theta + b. I think that somebody using this would want to tighten or loosen the spirals, or spiral in/out depending on what they wanted to do. Also- what happens when round gets big enough for the spirals to run into one another? Does it behave nicely? (ie - union).

**Comment by gmlewis** [comment]
We could add more parameters to the `Spiral2D`, but it seemed to me that one of the philosophies of this repo is to provide primitives that can be modified by other `SDF2` functions to shape it how we want. I believe that what you suggested can already be accomplished with scales and offsets, combined with modifying the `round` value. I'll work on coming up with an example later today to demonstrate what I mean.

As for making `round` unusually large, you basically get an outline of the entire spiral.

**Comment by gmlewis** [comment]
I'm on an Android phone... Let's see how this turns out.

Let's say you want the coil start point at (30,0) and end point at (60,0) (millimeters, for example). We want 10 crossings and spring width of 3.

```go
xs, xe, n, w := 30.0, 60.0, 10.0, 3.0
start := n*2.0*math.Pi
end := n*4.0*math.Pi
scale := xs/start
round := 0.5*w/scale
```

I'll try this out when I get home later today but I just wanted to capture my thoughts.

To get CCW, scale by a negative number.

**Comment by deadsy** [comment]
The parameters that need to be encoded for evaluating the SDF are sometimes not the same as the ones that you want to use to specify it. E.g. cams.go. I ended up having an X() function that returns the SDF and a MakeX() that uses design parameters, does the geometry and then returns the SDF. Suffice to say that the stored parameters are aimed at having a fast evaluation function while the design parameters are aimed at having an obvious mental model for the user. In the case of spirals my mental model goes towards:  blah( start, end V2, n uint, width float64) SDF2. Now is blah = Spiral2D or MakeSpiral2D? I don't know- but I'd like a function call that lets me specify a spiral like that - angles are often a pain to deal with. Someone needs to do an arctan and I'd rather someone else did it.

**Comment by gmlewis** [comment]
OK, great. Closing PR and will address it in my own repo then come back later with a proposal.

**Pull request closed without merging**
