### PR TITLE
Add RenderSVG support to sdfx

### PR DESCRIPTION
**Pull request by gmlewis**
This adds the ability to render SDF2 shapes to an SVG file.

### CODE REVIEW

**Comment by deadsy** [comment]
Ok- merged it. Is there something you can do to set a default stroke type for the lines in the svg file? When I open it with inkscape I see nothing. It's only when I select everything that I see there are lines in the file. Same deal with trying to open it in a web browser. I see nothing in chrome.

**Comment by gmlewis** [comment]
Thank you.

Yes, we could add a default stroke width so that it is visible upon opening and then provide a way to change it. I can add that if you would like.

**Comment by gmlewis** [comment]
Yes, in fact, I enjoy using https://github.com/ajstarks/svgo but I wasn't sure if you wanted to add another dependency to your repo.  I'm happy to switch it to that if you prefer.

**Comment by deadsy** [comment]
Yes - go ahead and use ajstarks/svgo. I took a look at it and it seems pretty light weight. I did a similar thing for the dxf support.

**Pull request merged**
